// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"qyx/internal/controllers"
	"qyx/internal/services"
	"qyx/pkg/start"
)

// Injectors from wire.go:

func CreateApp() *start.GinStart {
	engine := NewGinEngine()
	calculateService := services.NewCalculateService()
	calculateController := controllers.NewCalculateController(calculateService)
	startControllers := controllers.NewController(calculateController)
	ginStart := start.NewGinStart(engine, startControllers)
	return ginStart
}

// wire.go:

var providerSet = wire.NewSet(
	NewGinEngine, start.NewGinStart, controllers.ProviderSet, services.ProviderSet,
)
