// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"ly/config"
	"ly/internal/controllers"
	"ly/internal/repositories"
	"ly/internal/services"
	"ly/pkg/start"
)

// Injectors from wire.go:

func CreateApp() *start.GinStart {
	engine := NewGinEngine()
	db := config.InitMysqlClient()
	productRepository := repositories.NewProductRepository()
	productTypeRepository := repositories.NewProductTypeRepository()
	wareHostRepository := repositories.NewWareHostRepository()
	productService := services.NewProductService(db, productRepository, productTypeRepository, wareHostRepository)
	productController := controllers.NewProductController(productService)
	wareHostService := services.NewWareHostService(db, wareHostRepository, productService)
	wareHostController := controllers.NewWareHostController(wareHostService)
	productTypeService := services.NewProductTypeService(db, productTypeRepository, productService)
	productTypeController := controllers.NewProductTypeController(productTypeService)
	startControllers := controllers.NewController(productController, wareHostController, productTypeController)
	ginStart := start.NewGinStart(engine, startControllers)
	return ginStart
}

// wire.go:

var providerSet = wire.NewSet(
	NewGinEngine, start.NewGinStart, controllers.ProviderSet, services.ProviderSet, repositories.ProviderSet, config.ProviderSet,
)
